services:
  election-db:
    container_name: election_database
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=election_password123
      - POSTGRES_DB=election_db
